name: models
description: A Dart package that provides all models for mix car app.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  json_annotation: ^4.0.1

dev_dependencies:
  build_runner: ^2.0.5
  json_serializable: ^4.1.3