name: browse_products_repository
description: A Dart package that represents a browsing repo for product.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  json_annotation: ^4.0.1
  mix_api_provider:
    path: ../../providers/mix_api_provider
  models:
    path: ../../models

dev_dependencies:
  build_runner: ^2.0.5
  json_serializable: ^4.1.3
